DROP TABLE BAG;
CREATE TABLE BAG(
	BAG_PK INTEGER PRIMARY KEY,
	PRODUCT_PK INTEGER,
	MEMBER_PK INTEGER,
	PRODUCT_COUNT INTEGER,
	FOREIGN KEY (PRODUCT_PK) REFERENCES PRODUCT(PRODUCT_PK)
	ON DELETE CASCADE,
	FOREIGN KEY (MEMBER_PK) REFERENCES TBL_MEMBER(MEMBER_PK)
	ON DELETE CASCADE
);
-- SELECT * FROM BAG;

-- SELECT B.BAG_PK, B.PRODUCT_PK, B.PRODUCT_COUNT AS BAG_PRODUCT_COUNT, B.MEMBER_PK, P.PRODUCT_NAME, P.PRODUCT_PRICE, P.PRODUCT_COUNT, P.PRODUCT_BRAND 
-- FROM BAG B INNER JOIN PRODUCT P ON B.PRODUCT_PK = P.PRODUCT_PK WHERE B.MEMBER_PK = 10;

DROP SEQUENCE BAG_SEQ;
CREATE SEQUENCE BAG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

SELECT * FROM BAG;

SELECT B.BAG_PK, B.PRODUCT_PK, B.PRODUCT_COUNT AS BAG_PRODUCT_COUNT, B.MEMBER_PK,
P.PRODUCT_NAME, P.PRODUCT_PRICE, P.PRODUCT_COUNT, P.PRODUCT_BRAND
FROM BAG B INNER JOIN PRODUCT P ON B.PRODUCT_PK = P.PRODUCT_PK WHERE B.MEMBER_PK = 1101;
