/* CREATE TABLE TBL_MEMBER(
	MEMBER_PK INTEGER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30),
	MEMBER_NAME	VARCHAR2(30),
	MEMBER_PASSWORD VARCHAR2(30),
	MEMBER_ADDRESS VARCHAR2(30),
	MEMBER_PHONE_NUMBER VARCHAR2(30),
	MEMBER_ROLE VARCHAR2(30)
);*/
-- DROP TABLE TBL_MEMBER;
-- SELECT * FROM TBL_MEMBER;

--------------------------------------------------------

DROP TABLE TBL_MEMBER;
CREATE TABLE TBL_MEMBER (
 	MEMBER_PK INTEGER PRIMARY KEY,
 	MEMBER_ID VARCHAR(30),
 	MEMBER_NAME VARCHAR(30),
 	MEMBER_PASSWORD VARCHAR(30),
 	MEMBER_ADDRESS VARCHAR(30),
	MEMBER_PHONE_NUMBER VARCHAR(11),
	MEMBER_ROLE VARCHAR(30)
);
-- SELECT * FROM TBL_MEMBER;

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
START WITH 1101
INCREMENT BY 1
NOCACHE;


INSERT INTO TBL_MEMBER(MEMBER_PK, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_ADDRESS, MEMBER_PHONE_NUMBER, MEMBER_ROLE) 
	VALUES(MEMBER_SEQ.NEXTVAL,'admin','관리자','1234','강남','01012345678','ADMIN');
INSERT INTO TBL_MEMBER(MEMBER_PK, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_ADDRESS, MEMBER_PHONE_NUMBER, MEMBER_ROLE) 
	VALUES(MEMBER_SEQ.NEXTVAL,'test','테스트','1234','성남','01012341234','USER');
INSERT INTO TBL_MEMBER(MEMBER_PK, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_ADDRESS, MEMBER_PHONE_NUMBER, MEMBER_ROLE) 
	VALUES(MEMBER_SEQ.NEXTVAL,'NULL', '탈퇴한사용자' ,'1234','경기도','01011112222','QUIT');

SELECT * FROM TBL_MEMBER;
/*
INSERT INTO TBL_MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'TEEMO','김티모','1234','강동구','01012345678','USER');
INSERT INTO TBL_MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'asd123','모르가나','4321','북한','01012369643','ADMIN');
INSERT INTO TBL_MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'vvv321','니파리','0123','평양','01012369643','ADMIN');
INSERT INTO TBL_MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'ohb009','렝가','9981','함경도','01012369643','ADMIN');
INSERT INTO TBL_MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'ooppyy23','흐에이','0000','백두산','01012369643','ADMIN');--샘플
*/

-- UPDATE TBL_MEMBER SET MEMBER_ID = NULL, MEMBER_ROLE='QUIT' WHERE MEMBER_ID IS NULL  AND MEMBER_PASSWORD = 1234;

/*
SELECT * FROM TBL_MEMBER WHERE MEMBER_PASSWORD ='1234' AND MEMBER_ID = 'TEEMO';

SELECT MEMBER_PK, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_ADDRESS, MEMBER_PHONE_NUMBER, MEMBER_ROLE FROM TBL_MEMBER;
--전체 출력

SELECT MEMBER_PK, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_ADDRESS, MEMBER_PHONE_NUMBER, MEMBER_ROLE FROM TBL_MEMBER WHERE MEMBER_ID = 'TEEMO' AND MEMBER_PASSWORD = '1234';--로그인(LOGIN)   

SELECT MEMBER_PK, MEMBER_ID, MEMBER_NAME, MEMBER_PASSWORD, MEMBER_ADDRESS, MEMBER_PHONE_NUMBER, MEMBER_ROLE FROM TBL_MEMBER WHERE MEMBER_ID = 'asd123'; --회원가입 (JOIN)

UPDATE TBL_MEMBER SET MEMBER_ID = NULL WHERE MEMBER_ID = 'ooppyy23' AND MEMBER_PASSWORD = '0000';--회원탈퇴(update)

DELETE FROM TBL_MEMBER WHERE MEMBER_PK = 102;

INSERT INTO TBL_MEMBER VALUES('107','akkkk','트위치','4444','하와이','01077779999','USER'); --insert
*/
