CREATE TABLE PRODUCT(
	PRODUCT_ID INTEGER PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	PRICE INTEGER DEFAULT 0,
	COUNT INTEGER DEFAULT 0
);

INSERT ALL
	INTO PRODUCT VALUES(1001, '모니터', 100000, 3)
	INTO PRODUCT VALUES(1002, '키보드', 60000, 0)
	INTO PRODUCT VALUES(1003, '마우스', 50000, 5)
SELECT * FROM DUAL;

SELECT * FROM PRODUCT ORDER BY PRODUCT_ID ASC;

DROP TABLE PRODUCT;