DROP TABLE STUDENT;
--1
CREATE TABLE STUDENT(
	STUDENT_ID	INTEGER PRIMARY KEY,
	NAME 		VARCHAR(30) NOT NULL,
	SCORE 		INTEGER	DEFAULT 0
);
--2
INSERT ALL
	INTO STUDENT VALUES(1 ,'티모', 90)
	INTO STUDENT VALUES(2,'모르가나', 100)
	INTO STUDENT VALUES(3,'가렌', 73)
SELECT * FROM DUAL;
--3
INSERT INTO STUDENT VALUES((SELECT NVL(MAX(STUDENT_ID),0) FROM STUDENT)+1,'베인', 3);

--4
SELECT * FROM STUDENT ORDER BY STUDENT_ID ASC;
--5
SELECT NAME, SCORE FROM STUDENT WHERE SCORE>=80;
--6
SELECT * FROM STUDENT WHERE NAME LIKE '%가%';
--7
SELECT * FROM STUDENT WHERE SCORE>=50 AND NAME='가렌';
--8
SELECT COUNT(*) AS "학생수" FROM STUDENT;
--9
SELECT AVG(SCORE) AS "평균 점수" FROM STUDENT;

--10
UPDATE STUDENT SET SCORE=10 WHERE STUDENT_ID=2;

--11
DELETE FROM STUDENT WHERE STUDENT_ID=1;

DROP TABLE STUDENT;