CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(50) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	MID VARCHAR(30) NOT NULL,
	BCOUNT INT DEFAULT 0
);

DROP TABLE BOARD;



INSERT INTO BOARD(BID,TITLE,CONTENT,MID) VALUES((SELECT NVL(MAX(BID),100) FROM BOARD)+1,'제목','내용','admin');
INSERT INTO BOARD(BID,TITLE,CONTENT,MID) VALUES((SELECT NVL(MAX(BID),100) FROM BOARD)+1,'제목','내용','test');
INSERT INTO BOARD(BID,TITLE,CONTENT,MID) VALUES((SELECT NVL(MAX(BID),100) FROM BOARD)+1,'제제제','내용','test');
INSERT INTO BOARD VALUES((SELECT NVL(MAX(BID),100) FROM BOARD)+1,'공지','내용','admin',100);

SELECT * FROM BOARD;
SELECT * FROM BOARD ORDER BY BID DESC;
SELECT * FROM BOARD WHERE TITLE LIKE '%제%' ORDER BY BID DESC;
SELECT * FROM BOARD WHERE MID = 'admin' ORDER BY BID DESC;
SELECT * FROM BOARD ORDER BY BCOUNT DESC, BID DESC;

SELECT * FROM BOARD WHERE BID = 101;

DELETE FROM BOARD WHERE BID = 103;

UPDATE BOARD SET BCOUNT = BCOUNT+1 WHERE BID = 101;
UPDATE BOARD SET TITLE = '변경' WHERE BID = 101;
UPDATE BOARD SET CONTENT = '변경' WHERE BID = 101;