CREATE TABLE CONTENT(
	CONTENT_PK INT PRIMARY KEY,
	CONTENT VARCHAR2(4000)
);

CREATE SEQUENCE CONTENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

SELECT * FROM CONTENT ORDER BY CONTENT_PK DESC;

INSERT INTO CONTENT VALUES(CONTENT_SEQ.NEXTVAL, '아야어야오요우유');