CREATE TABLE MEMBER(
	MID VARCHAR(30) PRIMARY KEY,
	MPW VARCHAR(30) NOT NULL
);

INSERT ALL
	INTO MEMBER VALUES('teemo', '1234')
	INTO MEMBER VALUES('ari', '1234')
SELECT * FROM DUAL;

SELECT * FROM MEMBER;