CREATE TABLE MEMBER(
	MID VARCHAR(30) PRIMARY KEY,
	PASSWD VARCHAR(30) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	MROLE VARCHAR(30) NOT NULL
);

DROP TABLE MEMBER;



SELECT * FROM MEMBER;

SELECT * FROM MEMBER WHERE MID='teemo' AND PASSWD='1234';

INSERT INTO MEMBER VALUES('teemo','1234','김티모','USER');
INSERT INTO MEMBER VALUES('admin','1234','관리자','ADMIN');

UPDATE MEMBER SET NAME = '김티모' WHERE MID = 'teemo';

DELETE FROM MEMBER WHERE MID='test';