CREATE TABLE REPLY(
	RID INTEGER PRIMARY KEY,
	CONTENT VARCHAR(30),
	MID VARCHAR(30) ,
	REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	BID INTEGER NOT NULL,
	CONSTRAINT FK_MEMBER_REPLY FOREIGN KEY (MID) REFERENCES MEMBER(MID) ON DELETE CASCADE,
);

DROP TABLE REPLY;

INSERT INTO REPLY(RID,CONTENT, MID, BID) VALUES(1001, '댓글1', 'teemo', 103);
INSERT INTO REPLY(RID,CONTENT, MID, BID) VALUES(1002, '관리자의 댓글1', 'admin', 106);
INSERT INTO REPLY(RID,CONTENT, MID, BID) VALUES(1003, '댓글2', 'teemo', 103);
INSERT INTO REPLY(RID, CONTENT, MID, BID) VALUES((SELECT NVL(MAX(RID), 1000) FROM REPLY)+1, '댓글3', 'hurwan', 101);

SELECT * FROM BOARD;
SELECT * FROM MEMBER;
SELECT * FROM REPLY;

DELETE FROM MEMBER WHERE MID='hurwan';


-- 함꼐 삭제하는 방법
-- 1. M에서 SQL로 (DBMS 제약조건)으로 처리하는 방법
-- 2. CONTROLLER에서 로직(JAVA)으로 처리하는 방법