/*CREATE TABLE PRODUCT(
	PRODUCT_PK INTEGER PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(30),
	PRODUCT_PRICE INTEGER,
	PRODUCT_COUNT INTEGER,
	PRODUCT_BRAND VARCHAR2(30)
);*/
-- DROP TABLE PRODUCT;

-- SELECT * FROM PRODUCT;

------------------------------
--상품 테이블 생성
DROP TABLE PRODUCT;
CREATE TABLE PRODUCT( 
	PRODUCT_PK INTEGER PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(200),
	PRODUCT_PRICE INTEGER,
	PRODUCT_COUNT INTEGER,
	PRODUCT_BRAND VARCHAR2(30)
);

DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ
START WITH 101
INCREMENT BY 1
NOCACHE;

SELECT * FROM PRODUCT;
UPDATE PRODUCT SET PRODUCT_BRAND='더원스토리' WHERE PRODUCT_BRAND NOT IN ('더원스토리', '제이큐', '아트박스', '텐바이텐') OR PRODUCT_BRAND IS NULL;
-- UPDATE PRODUCT SET PRODUCT_BRAND = NULL WHERE PRODUCT_BRAND NOT IN ('더원스토리', '제이큐', '아트박스', '텐바이텐');
SELECT PRODUCT_BRAND, COUNT(*) FROM PRODUCT GROUP BY PRODUCT_BRAND;
-- SELECT COUNT(*) FROM PRODUCT;
-- SELECT PRODUCT_SEQ.NEXTVAL FROM DUAL;

-- 테이블 삭제
-- DROP TABLE PRODUCT; 

-- 전체 출력
-- SELECT * FROM PRODUCT;

--브랜드 전체 보기 // 중복은 제거
-- SELECT DISTINCT PRODUCT_BRAND FROM PRODUCT;

--PK 내림차순 출력
-- SELECT * FROM PRODUCT ORDER BY PRODUCT_PK DESC;

-- 상품 검색 출력
-- SELECT * FROM PRODUCT WHERE PRODUCT_NAME LIKE '%1%';

--가격 내림차순 출력
-- SELECT * FROM PRODUCT ORDER BY PRODUCT_PRICE DESC;

--가격 오름차순 출력
-- SELECT * FROM PRODUCT ORDER BY PRODUCT_PRICE;

--브랜드별 검색
-- SELECT * FROM PRODUCT WHERE PRODUCT_BRAND = '나이키';


-- 상품 추가하기
-- INSERT INTO PRODUCT VALUES(1,'상품01','1000','5','나이키');
-- INSERT INTO PRODUCT VALUES(2,'상품02','3000','9','아이다스');
-- INSERT INTO PRODUCT VALUES(3,'상품03','2000','2','나이키');


--상품pk와 상품의 재고를 받아 ++해야함
-- UPDATE PRODUCT SET PRODUCT_COUNT = PRODUCT_COUNT + 4 WHERE PRODUCT_PK = 2;


--상품pk와 상품의 재고를 받아 --해야함
-- UPDATE PRODUCT SET PRODUCT_COUNT = PRODUCT_COUNT - 4 WHERE PRODUCT_PK = 2;


--상품pk를 받아서 삭제
-- DELETE FROM PRODUCT WHERE PRODUCT_PK = 1;




