CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(30) NOT NULL,
	WRITER VARCHAR(30),
	CONTENT VARCHAR(30) NOT NULL
);

DROP TABLE BOARD;

INSERT INTO BOARD VALUES((SELECT NVL(MAX(BID),1000) FROM BOARD)+1,'공지01','admin','내용01');
INSERT INTO BOARD VALUES((SELECT NVL(MAX(BID),1000) FROM BOARD)+1,'공지02','admin','내용02');
INSERT INTO BOARD VALUES((SELECT NVL(MAX(BID),1000) FROM BOARD)+1,'공지03','admin','내용03');

INSERT INTO BOARD VALUES((SELECT NVL(MAX(BID),1000) FROM BOARD)+1,'글01',NULL,'t1');
INSERT INTO BOARD VALUES((SELECT NVL(MAX(BID),1000) FROM BOARD)+1,'글02',NULL,'t2');

SELECT * FROM BOARD ORDER BY BID DESC;

SELECT * FROM BOARD WHERE TITLE LIKE '%검색어%' ORDER BY BID DESC;

SELECT * FROM BOARD WHERE WRITER='검색어' ORDER BY BID DESC;

DELETE FROM BOARD WHERE WRITER='test';

UPDATE MEMBER SET TITLE='변경할제목' WHERE BID=1001;

SELECT * FROM BOARD WHERE BID=1001;
CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(30) NOT NULL,
	WRITER VARCHAR(30),
	CONTENT VARCHAR(30) NOT NULL
);
SELECT * FROM BOARD WHERE TITLE LIKE '%히히%' ORDER BY BID DESC;