CREATE TABLE MEMBER(
	MID VARCHAR(30) PRIMARY KEY,
	MPW VARCHAR(30) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	MROLE VARCHAR(30) DEFAULT 'USER'
);

DROP TABLE MEMBER;

INSERT INTO MEMBER VALUES('admin','1234','관리자','ADMIN');

SELECT * FROM MEMBER;

DELETE FROM MEMBER WHERE MID='admin';

UPDATE MEMBER SET NAME='변경할이름' WHERE MID='admin';

SELECT * FROM MEMBER WHERE MID='admin' AND MPW='1234';