CREATE TABLE REPLY(
	RID INT PRIMARY KEY,
	CONTENT VARCHAR(30) NOT NULL,
	WRITER VARCHAR(30),
	BID INT,
	FOREIGN KEY (BID) REFERENCES BOARD(BID) ON DELETE CASCADE
);

DROP TABLE REPLY;

INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),10000) FROM REPLY)+1,'댓글01','admin',1001);
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),10000) FROM REPLY)+1,'댓글02','admin',1001);

INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),10000) FROM REPLY)+1,'댓글01','admin',1002);
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),10000) FROM REPLY)+1,'댓글02','admin',1002);

INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),10000) FROM REPLY)+1,'댓글01','admin',1003);
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),10000) FROM REPLY)+1,'댓글02','admin',1003);



SELECT * FROM REPLY ORDER BY RID DESC;
SELECT * FROM REPLY WHERE BID=1001 ORDER BY RID DESC;

UPDATE REPLY SET CONTENT='변경할내용' WHERE RID=10001;